- package.json
As `cli.js` uses `tmp`, we need to define it in `dependencies` instead
of `devDependencies`. Otherwise we get an error `Cannot find module
'tmp'` when testing the module via the cli.
> Define `tmp` as `dependencies`

- lib/formatValues.js
- test/fixtures/values.css
- test/fixtures/values.out.css
If a value had already a space after a comma, `cssfmt` added a second
space.
input:
```
font: Arial, sans-serif;
```
output:
```
font: Arial,  sans-serif;
```
This commit fixes the regex in `lib/formatValues.js` by keeping only
one space after commas and removing the others.
> Keep only 1 space after commas and none before

- bin/cli.js
- package.json
- test/cli.js
In the CLI, if we don't specify a file to read, it reads the content from stdin.
This will help to build editors' plugin (see #7).
For instance, this allows us to run the command `:%!cssfmt` in Vim to format the current buffer.
Let me know if I've followed your JS coding style and if the tests I've added cover enough cases.
> Read file from stdin

- README.md
It adds the link for Vim's plugin `vim-cssfmt` in the Readme file.
It also removes the mention of the Vim's command since it doesn't handle error case: the buffer is overriden with the error message. Therefore it is better to use the plugin :)
> Add Vim plugin

- lib/formatComments.js
- test/fixtures/comment.css
- test/fixtures/comment.out.css
We checked `comment.parent.first` against `atrule`, which was always
undefined, instead of `comment`.
Add test to cover this fix.
> Fix atrule for comments format

- lib/config.js
When executing cssfmt in the cli, I got an error because indentWidth wasn't declared.
> Fix undefined indentWidth variable

- lib/config.js
- package.json
`cssfmt` is not necessarily executed at the same level as the `.editorconfig` file. Therefore we need to find the nearest config file.
See kewah/vim-cssfmt#1
> Find the nearest .editorconfig

- lib/formatAtRuleParams.js
- test/fixtures/sass-include-2.css
- test/fixtures/sass-include-2.out.css
CSSFmt is incorrectly adding extra spaces to @include calls:
```diff
- @include transform(translateZ(0) translateY(20px));
+ @include transform(translateZ (0) translateY (20px));
```
> Don't add extra spaces to @include parameters

- lib/formatAtRuleParams.js
- lib/formatAtRules.js
- test/fixtures/sass-include-2.css
- test/fixtures/sass-include-2.out.css
- Make sure that comments inside @include parameters are not removed
- Format comments inside @include parameters
- Don’t add extra empty lines to @include calls that are next to each
other
- Format multiple empty lines between @include calls to one empty line
- Add extra empty lines to @include calls that are between rules or
Sass blocks
> Sass @include fixes

- lib/formatColors.js
- test/fixtures/lowercase.css
- test/fixtures/lowercase.out.css
Currently named colors regex matches `tAn` from `animation: textAnimation 0.1s;`.
P.S.
I also have another bugfix coming for Sass math formatting.
> Make sure that named colors are not matched from a middle of a string

- lib/formatValues.js
- test/fixtures/content.css
- test/fixtures/content.out.css
- test/index.js
Currently CSSfmt trims whitespace inside string values:
```css
div {
content: "  test";
}
```
Gets changed to:
```css
div {
content: " test";
}
```
With one space removed.
> Don't replace spaces inside strings such as content property

- lib/formatAtRules.js
- test/fixtures/sass-include-2.css
- test/fixtures/sass-include-2.out.css
Currently CSSfmt turns:
```scss
@include retina { 
```
Into:
```scss
@include retina{ 
```
Removing a space before the curly brace.
> Don't remove space after @include param

- lib/formatSelectors.js
- test/fixtures/nested-2.css
- test/fixtures/nested-2.out.css
Currently CSSfmt is formatting:
```css
&:nth-child(5n+1) {
color: blue;
}
```
to this:
```css
&:nth-child(5n + 1) {
color: blue;
}
```
> Don't format nth-child params

- lib/formatDecls.js
- test/fixtures/ie-hacks.css
- test/fixtures/ie-hacks.out.css
- test/index.js
There are many CSS hacks that work for legacy Internet Explorer versions (http://codemug.com/html/css-hacks-for-ie6ie7ie8ie9-and-ie10/).
Currently CSSfmt turns this 
```css
.class {
*zoom: 1;
_width: 200px;
}
```
Into this:
```css
.class {
zoom: 1;
width: 200px;
}
```
> Make sure that Internet Explorer CSS hacks are not removed

- lib/formatSassVariables.js
- lib/formatValues.js
- test/fixtures/sass-math.css
- test/fixtures/sass-math.out.css
- Don’t format math operators inside function calls
- Don’t format math operators at the beginning of a string, but add
spaces before a number: `/[+\-*/%](?=\$|\()/g` => `/(?!^)[+\-*/%](?=\$|\(|\d)/g`
With this input:
```scss
$height: em(240/2);
$easing: cubic-bezier(.35, 0, .765, -0.120);
div {
margin-top: -($height/2);
}
```
CSSfmt output before:
```scss
$height: em(240 / 2);
$easing: cubic-bezier(.35, 0, .765, - 0.120);
div {
margin-top: - ($height/2);
}
```
and after fixes:
```scss
$height: em(240/2);
$easing: cubic-bezier(.35, 0, .765, -0.120);
div {
margin-top: -($height / 2);
}
```
> Math operator fixes

- lib/formatDecls.js
- test/fixtures/sass-mixin.css
- test/fixtures/sass-mixin.out.css
This change fixes a bug where indentation would not be correct because spaces where not trimmed from IE hacks (e.g. `*zoom: 1;`).
```scss
@mixin clearfix {
*zoom: 1;
&:before,
&:after {
display: table;
content: "";
}
&:after {
clear: both;
}
}
```
> Trim spaces from IE hacks

- lib/formatSelectors.js
- test/fixtures/nested-2.css
- test/fixtures/nested-2.out.css
Fix a formatting bug where CSSfmt is formatting this:
```css
> li > a {
}
```
...to this:
```css
> li> a {
}
```
> Fix formatting bug when using multiple direct child selectors

- lib/formatComments.js
- test/fixtures/sass-comment.css
- test/fixtures/sass-comment.out.css
Currently CSSfmt adds newlines to inline comments that are next to `@include` or `@extend`. This PR adds a check for atrules for the inline comment fix from https://github.com/morishitter/cssfmt/pull/57.
> Don't add newlines to Sass inline comments that are next to atrules

- lib/params.js
It seems to me that is need here :construction_worker:
> Missing option for `cosmiconfig`

- lib/formatOrder.js
- test/stylelint/declaration-block-properties-order-groups/.stylelintrc
- test/stylelint/declaration-block-properties-order-groups/declaration-block-properties-order-groups.css
- test/stylelint/declaration-block-properties-order-groups/declaration-block-properties-order-groups.out.css
Add support for groups in stylelint config:
```json
{
"rules": {
"declaration-block-properties-order": [
{
"properties": [
"font-size",
"font-weight"
]
},
"display",
"width",
"height",
"color",
"background",
"opacity"
]
}
}
```
Also it fixes #165.
> Add support for groups in `declaration-block-properties-order`

- bin/cli.js
For CI and pre-commit hooks, it would be useful to be able to pass a list of files to format in-place to the cli.
This PR adds this option to the cli (--list/-l could arguably be better named, lmk!)
More context: https://github.com/pre-commit/pre-commit/issues/394
> Added --list cli option to allow multiple in-place cli inputs

- lib/formatOrder.js
- test/stylelint/declaration-block-properties-order-severity/.stylelintrc
- test/stylelint/declaration-block-properties-order-severity/declaration-block-properties-order-severity.css
- test/stylelint/declaration-block-properties-order-severity/declaration-block-properties-order-severity.out.css
Right now using the `[["propertyOne", "propertyTwo"], {"severity": "warning"}]` format for `declaration-block-properties-order` results in silent failure and leaves the order unchanged. This should fix that case.
I did my best to do everything in the existing style but let me know if you would like anything changed to fit better and I'm happy to do it.
> Fix silent failure of format-order when config object is used

- .npmignore
... via `.npmignore`
`npm pack` results:
* With ignore file 15K, or 15855 Bytes
* Without ignore file 37K, or 37604 Bytes
Fixes #229
> Exclude files from npm package

- CHANGELOG.md
- README.md
- bin/cli.js
- package.json
- test/cli.js
> Add support for glob

- lib/formatAtRules.js
- test/css-modules/value/value.css
- test/css-modules/value/value.out.css
- test/index.js
@value is a valid CSS-module at-rule; ensure we don't do anything funky with spacing
* Added a test fixture for ensuring @values don't get an extra space
* Added fix in `formatAtRules` to account for @value
> Prevent space between EOL and semicolon for @value

- index.js
- lib/formatOrder.js
- package.json
- test/stylelint/order-declaration-block-order/.stylelintrc
- test/stylelint/order-declaration-block-order/order-declaration-block-order.css
- test/stylelint/order-declaration-block-order/order-declaration-block-order.out.css
- test/stylelint/order-declaration-block-property-groups-structure/.stylelintrc
- test/stylelint/order-declaration-block-property-groups-structure/order-declaration-block-property-groups-structure.css
- test/stylelint/order-declaration-block-property-groups-structure/order-declaration-block-property-groups-structure.out.css
Since "declaration-block-properties-order" rule is depracated I've updated formatOrder function to support both rules.
> stylelint-order plugin support

- README.md
- lib/formatDecls.js
- test/stylelint/declaration-empty-line-before-always-except/.stylelintrc
- test/stylelint/declaration-empty-line-before-always-except/declaration-empty-line-before-always-except.css
- test/stylelint/declaration-empty-line-before-always-except/declaration-empty-line-before-always-except.out.css
- test/stylelint/declaration-empty-line-before-always-ignore/.stylelintrc
- test/stylelint/declaration-empty-line-before-always-ignore/declaration-empty-line-before-always-ignore.css
- test/stylelint/declaration-empty-line-before-always-ignore/declaration-empty-line-before-always-ignore.out.css
- test/stylelint/declaration-empty-line-before-always/.stylelintrc
- test/stylelint/declaration-empty-line-before-always/declaration-empty-line-before-always.css
- test/stylelint/declaration-empty-line-before-always/declaration-empty-line-before-always.out.css
- test/stylelint/declaration-empty-line-before-never-except/.stylelintrc
- test/stylelint/declaration-empty-line-before-never-except/declaration-empty-line-before-never-except.css
- test/stylelint/declaration-empty-line-before-never-except/declaration-empty-line-before-never-except.out.css
- test/stylelint/declaration-empty-line-before-never-ignore/.stylelintrc
- test/stylelint/declaration-empty-line-before-never-ignore/declaration-empty-line-before-never-ignore.css
- test/stylelint/declaration-empty-line-before-never-ignore/declaration-empty-line-before-never-ignore.out.css
- test/stylelint/declaration-empty-line-before-never/.stylelintrc
- test/stylelint/declaration-empty-line-before-never/declaration-empty-line-before-never.css
- test/stylelint/declaration-empty-line-before-never/declaration-empty-line-before-never.out.css
see #256 
this supports everything except `ignore: ['inside-single-line-block']` which i think is related to `block-closing-brace-newline-before` support  (the code seems to work but a newline is always added before the closing brace).
> add support for declaration-empty-line-before

- lib/formatAtRules.js
- test/stylelint/at-rule-empty-line-before-always-except-all-nested/at-rule-empty-line-before-always-except-all-nested.css
- test/stylelint/at-rule-empty-line-before-always-except-all-nested/at-rule-empty-line-before-always-except-all-nested.out.css
Addresses one part of #280
Custom at-rules are no longer terminated with a space-semicolon, but instead just a semicolon.
before
```css
@custom-rule value ;
```
after
```css
@custom-rule value;
```
> Remove extra space for custom at-rules

- lib/formatAtRules.js
- test/stylelint/at-rule-empty-line-before-always-except-inside-block/.stylelintrc
- test/stylelint/at-rule-empty-line-before-always-except-inside-block/at-rule-empty-line-before-always-except-inside-block.css
- test/stylelint/at-rule-empty-line-before-always-except-inside-block/at-rule-empty-line-before-always-except-inside-block.out.css
Addresses one part of #280
at-rule newline rules weren't respected for the `inline-block` exception, which serves as the replacement to `all-nested`, deprecated in [stylelint 7.8.0](https://stylelint.io/CHANGELOG/#780).
This PR allows stylefmt to respect both forms of the option.
> at-rule-empty-line-before-always-except-inside-block

- lib/formatAtRules.js
- lib/formatRules.js
Some calls to `formatDecls` were missing the `stylelint` parameter. This fixes #256
> Pass the stylelint config to formatDecls when invoking it

- bin/cli.js
- package.json
Hey @morishitter! 
This swaps chalk for [Turbocolor](https://github.com/jorgebucaran/turbocolor).
It will give you a performance boost as turbocolor loads **_>20x_** faster and applies styles **_>18x_** faster than chalk for the same API (see [benchmarks](https://github.com/jorgebucaran/turbocolor/tree/master/bench#benchmarks)). 
<pre>
chalk: 15.190ms
<b>turbocolor: 0.777ms</b>
chalk × 8,729 ops/sec
<b>turbocolor × 158,383 ops/sec</b>
chalk × 1,838 ops/sec
<b>turbocolor × 39,830 ops/sec</b>
chalk × 4,049 ops/sec
<b>turbocolor × 59,833 ops/sec</b>
</pre>
Let me know if this is acceptable to you or if you want to refactor anything. 
Cheers!
> Swap chalk for turbocolor.

- bin/cli.js
- package.json
- yarn.lock
Hi @morishitter! This PR swaps minimist for [getopts](https://github.com/jorgebucaran/getopts) for more perf gains (full benchmarks [here](https://github.com/jorgebucaran/getopts/tree/master/bench)).
<pre>
mri × 374,999 ops/sec
yargs × 32,370 ops/sec
<b>getopts × 1,495,165 ops/sec</b>
minimist × 283,031 ops/sec
</pre>
Getopts has essentially the same API as minimist, so this is effectively a "drop-in" replacement. I think minimist is a great package, but also too difficult to contribute to (34 open issues and 26 pull requests, but no updates since 2015).
Let me know if this looks good to you. Cheers!
> Swap minimist for getopts for more perf gains!
