morishitter/stylefmt

README.md

Install cssfmt globally

---

bin/cli.js

Change the version flag name to `--version` (instead of `--versions`).

Fix `--version` flag name

---

lib/formatAtRules.js
test/fixtures/charset-2.css
test/fixtures/charset-2.out.css
test/fixtures/charset.css
test/fixtures/charset.out.css
test/index.js

CSSFmt is incorrectly changing:
```diff
-@charset "utf-8";
+@charset "utf-8" ;
```

Fix @charset formatting

---

index.js
lib/config.js
lib/getIndent.js
lib/hasDecls.js
lib/hasRules.js
lib/util.js
package.json

- Replace editorconfig-indent and find-config to editorconfig-core-js
- Improve search of rule.nodes type
- Tweak duplicate code

Introduce editorconfig-core-js

---

README.md

* Fixed several spacing and spelling errors.
* Changed "Example" to "Examples".
* Edited Features section, adding consistent, active verbs.

Edited README.MD for typos, spelling, and clarity

---

bin/cli.js

fixed the bug occurs with `—recursive` option.

fix/recursive. fix #127

---

lib/formatDecls.js
test/sass/sass-variables/sass-variables.css
test/sass/sass-variables/sass-variables.out.css

do not format to lowercase when decl.prop is sass variable

---

lib/formatValues.js
test/fixtures/font-face/font-face.css
test/fixtures/font-face/font-face.out.css

do not add spaces in font-family value

---

CHANGELOG.md
lib/formatDecls.js
lib/formatRules.js
package.json
test/stylelint/declaration-colon-space-after-never/.stylelintrc
test/stylelint/declaration-colon-space-after-never/declaration-colon-space-after-never.css
test/stylelint/declaration-colon-space-after-never/declaration-colon-space-after-never.out.css
test/stylelint/declaration-colon-space-before-always/.stylelintrc
test/stylelint/declaration-colon-space-before-always/declaration-colon-space-before-always.css
test/stylelint/declaration-colon-space-before-always/declaration-colon-space-before-always.out.css

support declaration colon space rules of stylelint

---

lib/formatAtRules.js
lib/formatColors.js
lib/formatDecls.js
lib/formatRules.js
lib/formatSelectors.js
lib/formatTransforms.js
lib/formatValues.js
lib/util.js
test/fixtures/nested-indention-2/nested-indention-2.css
test/fixtures/nested-indention-2/nested-indention-2.out.css
test/fixtures/nested-indention-2/stylelint.config.js
test/fixtures/nested-indention/nested-indention.css
test/fixtures/nested-indention/nested-indention.out.css
test/fixtures/nested-indention/stylelint.config.js

Fixes #137. Modify format rules for selector-list-comma-newline-before and block-opening-brace-newline-before.

Fix nested indention

---

lib/formatAtRules.js
test/stylelint/block-opening-brace-newline-before-always/block-opening-brace-newline-before-always.css
test/stylelint/block-opening-brace-newline-before-always/block-opening-brace-newline-before-always.out.css

support block-opening-brace-newline-before rule in atrule

---

lib/formatSelectors.js
test/fixtures/attr-selector/attr-selector.css
test/fixtures/attr-selector/attr-selector.out.css

fixed #146

---

CHANGELOG.md
README.md
lib/formatAtRules.js
lib/formatComments.js
lib/formatRules.js
package.json
test/fixtures/comment-in-rules/comment-in-rules.out.css
test/fixtures/comment/comment.css
test/fixtures/comment/comment.out.css
test/fixtures/cssnext-example/cssnext-example.css
test/fixtures/cssnext-example/cssnext-example.out.css
test/fixtures/inline-comment/inline-comment.css
test/fixtures/inline-comment/inline-comment.out.css
test/fixtures/readme/readme.css
test/fixtures/readme/readme.out.css
test/sass/sass-comment/sass-comment.css
test/sass/sass-comment/sass-comment.out.css
test/sass/sass-content/sass-content.css
test/sass/sass-content/sass-content.out.css
test/sass/sass-include-2/sass-include-2.css
test/sass/sass-include-2/sass-include-2.out.css
test/sass/sass-inline-comment/sass-inline-comment.css
test/sass/sass-inline-comment/sass-inline-comment.out.css
test/sass/sass-single-at-rule/sass-single-at-rule.out.css
test/sass/scss/scss.css
test/stylelint/extends/extends.css
test/stylelint/extends/extends.out.css
test/stylelint/extends2/extends2.out.css

https://github.com/morishitter/stylefmt/issues/158

Changed not allow to format lines and spaces before and after comments

---

lib/params.js
test/stylelint/indentation-2space-severity/.stylelintrc
test/stylelint/indentation-2space-severity/indentation-2space-severity.css
test/stylelint/indentation-2space-severity/indentation-2space-severity.out.css
test/stylelint/indentation-4space-severity/.stylelintrc
test/stylelint/indentation-4space-severity/indentation-4space-severity.css
test/stylelint/indentation-4space-severity/indentation-4space-severity.out.css
test/stylelint/indentation-tab-severity/.stylelintrc
test/stylelint/indentation-tab-severity/indentation-tab-severity.css
test/stylelint/indentation-tab-severity/indentation-tab-severity.out.css

If you would like to support severities this should allow them with the indentation rule.
Similar updates would need to be done for all other rules.
This fixes #170

Support for severities with indentation rules

---

README.md

My loader uses stylefmt to fix stylint issues while webpack bundles an application.

Adding my webpack-loader if the authors are interested

---

package.json

Fixes or at least starts the discussion for #184

Define the minimum Node.js version

---

.travis.yml
index.js
package.json

Drop Node.js v0.12

---

lib/formatAtRules.js
lib/formatComments.js
lib/formatDecls.js
lib/formatRules.js
lib/getIndent.js
lib/params.js
package.json

we can use `String.prototype.repeat()` because we dropped to support node v0.12.

use String.prototype.repeat() instead of repeat-string

---

README.md
lib/formatShorthand.js
lib/formatValues.js
lib/formatZeros.js
package.json
test/stylelint/number-leading-zero-always/.stylelintrc
test/stylelint/number-leading-zero-always/number-leading-zero-always.css
test/stylelint/number-leading-zero-always/number-leading-zero-always.out.css
test/stylelint/number-leading-zero-never/.stylelintrc
test/stylelint/number-leading-zero-never/number-leading-zero-never.css
test/stylelint/number-leading-zero-never/number-leading-zero-never.out.css
test/stylelint/number-no-trailing-zeros/.stylelintrc
test/stylelint/number-no-trailing-zeros/number-no-trailing-zeros.css
test/stylelint/number-no-trailing-zeros/number-no-trailing-zeros.out.css
test/stylelint/shorthand-property-no-redundant-values/.stylelintrc
test/stylelint/shorthand-property-no-redundant-values/shorthand-property-no-redundant-values.css
test/stylelint/shorthand-property-no-redundant-values/shorthand-property-no-redundant-values.out.css

Hi! Added some new rules support.

New rules support

---

lib/formatZeros.js
test/stylelint/number-leading-zero-always/number-leading-zero-always.css
test/stylelint/number-leading-zero-always/number-leading-zero-always.out.css
test/stylelint/number-leading-zero-never/number-leading-zero-never.css
test/stylelint/number-leading-zero-never/number-leading-zero-never.out.css

Hi!
Fixed a bug for my last PR + added test case.

Fix bug at number-leading-zero feature

---

.eslintrc.json
bin/cli.js
lib/formatAtRuleParams.js
lib/formatAtRules.js
lib/formatColors.js
lib/formatOrder.js
lib/formatRules.js
lib/formatSassVariables.js
lib/formatShorthand.js
lib/formatValues.js
lib/formatZeros.js
lib/hasBlock.js
lib/params.js
lib/util.js
package.json

I've seen recently added feature and formatted some codes.
Is that convenient for you ?

Improve .eslintrc.json

---

bin/cli.js
test/cli.js

rename --list option to --recursive

---

bin/cli.js
lib/params.js
package.json

Beautify the CLI output

---

lib/formatSassVariables.js
test/stylelint/length-zero-no-unit/length-zero-no-unit.css
test/stylelint/length-zero-no-unit/length-zero-no-unit.out.css
test/stylelint/number-leading-zero-always/number-leading-zero-always.css
test/stylelint/number-leading-zero-always/number-leading-zero-always.out.css
test/stylelint/number-leading-zero-never/number-leading-zero-never.css
test/stylelint/number-leading-zero-never/number-leading-zero-never.out.css
test/stylelint/number-no-trailing-zeros/number-no-trailing-zeros.css
test/stylelint/number-no-trailing-zeros/number-no-trailing-zeros.out.css

Format zeros in root scope Sass variables

---

bin/cli.js

Support css file name in wechat app project.

support wxss #254

---

lib/formatDecls.js
test/stylelint/declaration-empty-line-before-always-standard/.stylelintrc
test/stylelint/declaration-empty-line-before-always-standard/declaration-empty-line-before-always-standard.css
test/stylelint/declaration-empty-line-before-always-standard/declaration-empty-line-before-always-standard.out.css

fix indentation inside of at statements

---

lib/formatAtRules.js
lib/formatComments.js
lib/formatDecls.js
lib/formatRules.js

Fixes #276 
This is kind of a gross hack, but it works.

Guard against raws.before being undefined

---

lib/formatZeros.js
test/stylelint/number-leading-zero-always/number-leading-zero-always.css
test/stylelint/number-leading-zero-always/number-leading-zero-always.out.css
test/stylelint/number-leading-zero-never/number-leading-zero-never.css
test/stylelint/number-leading-zero-never/number-leading-zero-never.out.css
test/stylelint/number-no-trailing-zeros/number-no-trailing-zeros.css
test/stylelint/number-no-trailing-zeros/number-no-trailing-zeros.out.css

Update formatZeros regular expressions

---

bin/cli.js

Add support for *.less and *.pcss files in recursive cli mode

---

CHANGELOG.md
bin/cli.js
package.json

@morishitter 👋 Replace turbocolor (name and implementation changed) with colorette.

refactor: replace turbocolor with colorette
